// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbmtebivnmemebqkadeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRibXRlYml2bm1lbWVicWthZGVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMjg1NTEsImV4cCI6MjA2MDgwNDU1MX0.rimmBf2XjmA1DH8VG72--nVY7vyZKpnwHUnjqIjw1ZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);